### ISSUE TITLE
Deal with rXXXi1p1f1

### ISSUE THREAD

**Issue by lee1043** [durack1/durolib#40]
Some of CMIP6 model has 3 digit number for r index for the realization. 

https://github.com/durack1/durolib/blob/4a1c4e47f94e94653e34749bcbc0370ef574d548/durolib/durolib.py#L1187

Above line may need to be changed accordingly to prevent error from below part:

https://github.com/durack1/durolib/blob/4a1c4e47f94e94653e34749bcbc0370ef574d548/durolib/durolib.py#L1192

**Comment by lee1043** [comment]
@durack1 does this make sense to you? Any chance this update to be applied for the conda version install sometime soon?

I know it must be an easy and quick fix, but I am struggling to make the revised durolib code from my own git branch to be imported from python even after `setup.py install`, because the python keeps loading the conda installed version of durolib.

**Comment by pochedls** [comment]
@lee1043 - I leave it to @durack1 to decide on what to do about this, but there is a newer (less tested) version of trimModelList [here](https://github.com/PCMDI/climlib/blob/master/climlib/wrangle.py).

**Comment by lee1043** [comment]
@pochedls thanks for the information. That looks like a good workaround option.

**Comment by durack1** [comment]
@lee1043 I agree with @pochedls rather than scatter things around separate repos it would be worthwhile migrating all useful (py2 and py3) tested functions into [climlib](https://github.com/PCMDI/climlib/blob/master/climlib/wrangle.py). Much of the durolib code has problems with py3, and diverting energy across repos seems like a waste of limited effort.

Once climlib is a little more developed, it would be nice to wrap this into a conda package with comprehensive versioning so we can easily access the library. Please feel free to contribute functions into the library as well, we really want to leverage code that folks are sharing around in B170 so that we can all benefit, and not reinvent the wheel even though we're literally sitting on the same floor of the building.

I will close this issue as I think the discussion below warrants it
